ComPWA/ampform

docs/bibliography.bib
docs/usage/dynamics/lineshapes.ipynb
src/ampform/dynamics/lineshape.py

- Improved rendering of the `BlattWeisskopf` in the API and the lineshape notebook
- Extended the Blatt-Weisskopf definition to angular momentum of up to 8

feat: extend Blatt-Weisskopf to L <= 8

---

docs/usage/dynamics/custom.ipynb
src/ampform/dynamics/builder.py

Made the custom dynamics instructions a bit more user-friendly by:
- putting the `import` statements where they are used (for copy-button)
- clarifying what the output of a custom dynamics builder is by declaring an `expression` and `parameter_defaults` parameter

docs: improve custom dynamics instructions

---

.cspell.json
.editorconfig
.gitignore
.pre-commit-config.yaml
.prettierignore
.vscode/settings.json
reqs/3.6/requirements-dev.txt
reqs/3.6/requirements-doc.txt
reqs/3.6/requirements-extras.txt
reqs/3.6/requirements-sty.txt
reqs/3.6/requirements-test.txt
reqs/3.6/requirements.txt
reqs/3.7/requirements-dev.txt
reqs/3.7/requirements-doc.txt
reqs/3.7/requirements-extras.txt
reqs/3.7/requirements-sty.txt
reqs/3.7/requirements-test.txt
reqs/3.7/requirements.txt
reqs/3.8/requirements-dev.txt
reqs/3.8/requirements-doc.txt
reqs/3.8/requirements-extras.txt
reqs/3.8/requirements-sty.txt
reqs/3.8/requirements-test.txt
reqs/3.8/requirements.txt
reqs/3.9/requirements-dev.txt
reqs/3.9/requirements-doc.txt
reqs/3.9/requirements-extras.txt
reqs/3.9/requirements-sty.txt
reqs/3.9/requirements-test.txt
reqs/3.9/requirements.txt

Use the new `check-dev-files` hook to rename and format the `.cspell.json` file.

ci: standardize cspell config

---

src/ampform/dynamics/lineshape.py

(Also serves as test for epic branches.)

feat: specify BlattWeisskopf signature

---

docs/usage/interactive.ipynb

Addendum to #23. It fixes problems like [this one](https://readthedocs.org/projects/ampform/builds/13499438/) on RTD, as well as when running `tox -e doc` locally.

fix: only render gif if it has been generated

---

.cspell.json
.gitpod.yml
.pre-commit-config.yaml
pytest.ini
tox.ini

Since 35aa838, it is become impossible to run tests through VSCode. Defining testpaths fixes this. In addition, it removes the last
'non-tox' section from the tox.ini file (see 81402eb).
See also https://github.com/ComPWA/qrules/pull/42

fix: define testpaths in pytest.ini

---

.constraints/py3.6.txt
.constraints/py3.7.txt
.constraints/py3.8.txt
.constraints/py3.9.txt
.cspell.json
.pre-commit-config.yaml
setup.cfg

Pre-commit hooks should only be local if the corresponding tool can also be used through other applications (e.g. IDEs or Jupyter Lab), so that their versions are in sync. And `nbstripout` can only be used through the terminal, so is best enforced through pre-commit only.

build: move nbstripout to pre-commit

---

.flake8
docs/conf.py
docs/extend_docstrings.py
docs/usage/dynamics/lineshapes.ipynb
pytest.ini
src/ampform/dynamics/__init__.py

The `lineshapes` notebook was used to insert a mathematical rendering of the implementations in the dynamics module into its docstrings. This has some disadvantages:
- Output cells have to be updated whenever some implementation. This could be countered with pytest-notebook, but that is bothersome if a notebook generates figures.
- The link between the module and that notebook is note immediately clear.
The math is now inserted through Sphinx only (through `conf.py`), which makes it easier to extend the `dynamics` module with more lineshapes and render their mathematics.

docs: remove myst-nb glue cells

---

docs/extend_docstrings.py

#42 makes it easier to dynamically generate latex for the math in behind the `dynamics` module. This makes it easier to cross-reference the formulas as follows:
<details>
<summary>Screenshot of generated API</summary>
</details>
It now also becomes easier to extract for instance running width (both in coding and in math definitions).

docs: improve math in dynamics API

---

docs/extend_docstrings.py
docs/usage/k-matrix.ipynb
src/ampform/dynamics/__init__.py

The running width / coupled width / mass dependent width used in `relativisitc_breit_wigner_with_ff` is useful to _K_-matrix and Flatté. It's now exposed as a separate function:

refactor: extract function for coupled width

---

.constraints/py3.6.txt
.constraints/py3.7.txt
.constraints/py3.8.txt
.constraints/py3.9.txt
docs/extend_docstrings.py
docs/usage/dynamics/k-matrix.ipynb
setup.cfg
src/ampform/dynamics/__init__.py
src/ampform/dynamics/builder.py

The original `breakup_momentum` contains a `sqrt`. This is inconvenient for the caller, because it does not allow handling negative values the break-up momentum _squared_. This is becomes important in phase space factors.

refactor: return square value of break-up momentum

---

docs/extend_docstrings.py
docs/usage/amplitude.ipynb
docs/usage/dynamics/analytic-continuation.ipynb
docs/usage/dynamics/lineshapes.ipynb
src/ampform/dynamics/__init__.py
src/ampform/dynamics/builder.py
src/ampform/dynamics/decorator.py
src/ampform/helicity.py
tests/test_dynamics.py

Implement `phase_space_factor` introduced by #51 into the `coupled_width`. The 'default' `phase_space_factor` has been adapted so that it can handle negative square roots.
Note: the overall lineshape of amplitude models does not change in the domain where it was defined so far. Only undefined domains are extended (see `test_dynamics.py`).

refactor!: implement analytic continuation

---

docs/extend_docstrings.py
docs/usage/dynamics/k-matrix.ipynb
docs/usage/dynamics/lineshapes.ipynb
src/ampform/dynamics/__init__.py
src/ampform/dynamics/builder.py

The value of Blatt-Weisskopf squared can be negative. This leaves it up to the caller how to handle these negative values if a square root is to be taken. Note that this becomes particularly important when the Blatt-Weisskopf function is used as a damping factor, like in `relativistic_breit_wigner_with_ff` and `create_non_dynamics_with_ff`, as opposed to `coupled_width` (where the square value is used).
Also improved some of the references for the lineshapes. In addition, a new interactive widget shows the effect of a Blatt-Weisskopf factor.

refactor!: switch to Blatt-Weisskopf squared

---

docs/extend_docstrings.py
src/ampform/dynamics/__init__.py

The signature of functions that have arguments with functions as default values (for an argument that expects a callable) do not render well. So it's better to use `Optional[PhaseSpaceFactor] = None` instead.

refactor: improve signature of coupled_width

---

.cspell.json
docs/extend_docstrings.py
docs/usage/dynamics.ipynb
docs/usage/dynamics/analytic-continuation.ipynb
src/ampform/dynamics/__init__.py

`phase_space_factor_ac` was taken from ComPWA, but this contained terms involving `s` that are already in the original `phase_space_factor` (which comes from the PDG, not ComPWA). In addition, the analytic continuation re-used the standard 'standard' `phase_space_factor`, which uses `complex_sqrt`. This has been fixed as well.

fix!: remove faulty terms in analytic continuation

---

.cspell.json
docs/usage/amplitude.ipynb

The complete amplitude model can only be rendered if [`jupyterlab-katex`](https://pypi.org/project/jupyterlab-katex) is installed. However, since KaTeX is less extensive than MathJax, this is only pointed out as a tip, and `jupyterlab-katex` is not added to the requirements.

docs: add tip about jupyter-katex

---

.cspell.json
.flake8
docs/conf.py
docs/extend_docstrings.py
docs/usage/dynamics.ipynb
docs/usage/dynamics/analytic-continuation.ipynb
pytest.ini
src/ampform/dynamics/__init__.py
src/ampform/dynamics/math.py
tests/test_dynamics.py

Closes #64 
Implements [TR-000](https://compwa-org.readthedocs.io/report/000.html) and [TR-001](https://compwa-org.readthedocs.io/report/001.html) by defining a `ComplexSqrt` class. This allows for custom lambdification for specific expression tree nodes that are a square root.

fix!: add control over complex square roots

---

src/ampform/data.py

Since #75 there is no need to use complex values as input for analytic continuation.

fix: return float masses if possible

---

src/ampform/dynamics/builder.py

Added a new function to `ampform.dynamics.builder` that allows setting a `relativistic_breit_wigner_with_ff` with analytic continuation.

feat: define builder for analytic continuation

---

docs/conf.py
docs/index.md
docs/usage/dynamics.ipynb
src/ampform/dynamics/__init__.py

Some links in the `expertsystem`, because [intersphinx](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html) is a bit too eager.

fix: remove links to expertsystem

---

docs/extend_docstrings.py
src/ampform/dynamics/__init__.py

It makes more sense to use `breakup_momentum` as an argument to `phsp_factor` in `relativistic_breit_wigner_with_ff` etc than `breakup_momentum_squard`.

feat: define breakup_momentum

---

.flake8
.pydocstyle
docs/extend_docstrings.py
src/ampform/helicity/__init__.py
src/ampform/helicity/decay.py
src/ampform/kinematics.py

Added several examples that explain the implementations in the `helicity` and `kinematics` modules.
A preview of the API can be viewed here:
https://ampform--100.org.readthedocs.build/en/100/api/ampform.html

docs: extend docstrings helicity and kinematics

---

docs/extend_docstrings.py
docs/usage/amplitude.ipynb
docs/usage/dynamics.ipynb
docs/usage/dynamics/analytic-continuation.ipynb
docs/usage/dynamics/custom.ipynb
docs/usage/dynamics/k-matrix.ipynb
docs/usage/formalism.ipynb
docs/usage/interactive.ipynb
docs/usage/modify.ipynb
docs/usage/symplot.ipynb

Widen cells where their input and/or output is so wide that a horizontal scrollbar appears. This can be done with the `full-width` tag:
https://sphinx-book-theme.readthedocs.io/en/latest/layout.html#full-width-content
For instance:
versus ([v0.10.3](https://ampform.readthedocs.io/en/0.10.3/usage/amplitude.html#build-sympy-expression)):

docs: widen cell output where needed

---

docs/usage/dynamics/k-matrix.ipynb
docs/usage/interactive.ipynb
docs/usage/symplot.ipynb
src/symplot/__init__.py
tests/symplot/test_symplot.py

Some minor changes that improve usage of `symplot`, but don't affect interface. Required for https://github.com/ComPWA/compwa-org/pull/37.

feat: improve usage of symplot.SliderKwargs

---

src/ampform/dynamics/__init__.py
src/ampform/dynamics/builder.py
src/ampform/dynamics/decorator.py
src/ampform/helicity/__init__.py

This check makes the framework less flexible and the additional code is not worth the 'friendly' exception. It is required for https://github.com/ComPWA/compwa-org/pull/37, where a special class `PhaseSpaceFactor` is inserted into `coupled_width`.

refactor: remove verify_signature

---

src/ampform/__init__.py
src/ampform/dynamics/__init__.py
src/ampform/dynamics/decorator.py

Fixes a small bug that was introduced by the new function `create_expression`, which was introduced in #113. That function allowed handling the `deep` argument in `doit`, so that expressions containing a `BlattWeisskopfSquared` can be called with `doit(deep=False)`. The fix was faulty though; this PR is the correct implementation.

fix: implement deep argument in doit, not new

---

src/ampform/dynamics/__init__.py
src/ampform/sympy.py

The `ampform.dynamics.decorator` sub-module does more than just providing decorators. It generally contains functions that help building `sympy.Expr` classes (and instances), so it is better moved and renamed to a more general place: `ampform.sympy`.

refactor: rename decorator sub-module to sympy

---

src/ampform/dynamics/__init__.py
src/ampform/sympy.py

Added an instance attribute to `UnevaluatedExpr` so that it can be used in the LaTeX rendering. In addition, the LaTeX rendering of of classes like `PhaseSpaceFactor` is affected by the name of their arguments (if they have any). This comes in handy in the relativistic K-matrix, when we want to distinguish between different `CoupledWidth`s and `PhaseSpaceFactor`s in the LaTeX rendering.

feat: allow modify expression names

---

docs/usage/dynamics/k-matrix.ipynb
src/ampform/dynamics/kmatrix.py

Previously, rho dagger was erroneously taken to be the conjugate of the inverse (should be transpose). This fixes this error. It also extracts the rho-matrix construction to a separate function.
There was also a small bug in the _P_-vector: matrix size of _P_ and _K_ had been swapped.
---
Original:
New:

fix!: define sqrt rho dagger as conjugate only

---

docs/usage/dynamics/k-matrix.ipynb
src/ampform/dynamics/kmatrix.py
tests/dynamics/test_kmatrix.py

All arguments named `n_resonances` have been renamed `n_poles`. The formulations in the theory section for the _K_-matrix now also prefer "pole" over "resonance".

refactor!: use n_poles instead of n_resonances

---

docs/usage/dynamics/k-matrix.ipynb
pytest.ini
src/ampform/dynamics/__init__.py
tests/test_dynamics.py

Specifically for speeding up the widgets, see e.g. ad65784

feat: allow limiting ang momentum in BlattWeissk

---

src/ampform/dynamics/__init__.py
src/ampform/sympy.py

The `name` instance attribute for classes that derive from `UnevaluatedExpression` not really meant to be part of the interface and clogs the API:

refactor: hide name attribute from UnevaluatedExpr

---

docs/usage/amplitude.ipynb
src/ampform/sympy.py
tests/dynamics/test_sympy.py

A pickled `HelicityModel` could not be unpickled again, because the `UnevaluatedExpression._name` attribute was stored as a positional (i.e. required) argument in [`__getnewargs__`](https://docs.python.org/3/library/pickle.html#object.__getnewargs__).

fix: correctly pickle UnevaluatedExpression

---

src/ampform/dynamics/__init__.py
tests/test_dynamics.py

`CoupledWidth` class did not set its `phsp_factor` attribute if it was specified in the constructor.

fix: correctly set custom phsp_factor CoupledWidth

---

src/ampform/dynamics/__init__.py
tests/dynamics/test_sympy.py
tests/test_dynamics.py

`CoupledWidth._name` can now be set through the constructor, just like other classes that derive from `UnevaluatedExpression`.

feat: set CoupledWidth name through constructor

---

src/ampform/sympy.py

The `implement_doit_method` decorator would re-construct the class from its own arguments. It's better to directly call the `evaluate()` method though, because the class is already constructed once the method is called.

fix: simplify doit implementation

---

src/ampform/dynamics/__init__.py

The docstring for `relativistic_breit_wigner_with_ff` still included a note about setting the damping factor to zero below threshold in case of zero angular momentum.

fix: remove 0-below-threshold note for rel BW

---

src/ampform/dynamics/__init__.py

Just like with `CoupledWidth`, the (optional) subscript in the latex rendering for this function should come from the decaying parameter (input argument `s`), not the decay products (input argument `m_a`).

fix: determine phase space factor subscript from s

---

docs/conf.py
src/ampform/helicity/__init__.py

`HelicityModel.components` and `HelicityModel.parameter_defaults` are now ordered alphabetically, so that you can also get them by index. ([Not entirely straight-forward](https://stackoverflow.com/a/10058239/13219025), but at least now it's guaranteed that the items are orderd.)

feat: order components and parameter defaults

---

docs/abbreviate_signature.py
src/ampform/helicity/__init__.py

Previously, `OrderedDict` was imported from `typing-extensions`. This seems to work better for typing than `collections.OrderedDict`, but is only available in `typing-extensions==3.10.*`, see e.g.
https://github.com/ComPWA/tensorwaves/pull/327/checks?check_run_id=3717304158
Setting `typing-extensions>=3.10` as a lower limit however causes problems downstream for packages that use TensorFlow, see e.g. https://github.com/ComPWA/tensorwaves/pull/317
For now, it's therefore better to use collections.OrderedDict instead, so that there is no need to restrict typing-extensions.

fix: import OrderedDict from collections

---

src/ampform/helicity/__init__.py

This inline fix is not required anymore since https://github.com/sympy/sympy/pull/21769. This fix was released with [SymPy v1.9](https://github.com/sympy/sympy/wiki/release-notes-for-1.9).
Note that a minimum version for SymPy is not specified in `setup.cfg`. This is done on purpose because the fix is not crucial for performance of the helicity model building.
https://github.com/ComPWA/ampform/blob/5abe1f/setup.cfg#L48

chore: remove CG latex fix

---

pyproject.toml
src/ampform/dynamics/__init__.py
src/ampform/sympy.py

The `@implement_doit_method` decorator was using one inline function layer too many. So now you have to write 
```python
@implement_doit_method
class MyExpr(UnevaluatedExpression):
...
```
instead of
```python
@implement_doit_method()
class MyExpr(UnevaluatedExpression):
...
```

fix: simplify implement_doit_method decorator

---

docs/extend_docstrings.py
docs/usage/dynamics.ipynb
docs/usage/dynamics/analytic-continuation.ipynb
docs/usage/dynamics/k-matrix.ipynb
src/ampform/dynamics/__init__.py
src/ampform/dynamics/kmatrix.py
tests/dynamics/test_sympy.py
tests/test_dynamics.py

`CoupledWidth` was a bit confusing. More common terms are mass/energy dependent width or running width.
_This PR should be merged later on (or in an epic branch), so that it can be released in v0.12.0 (interface change)._

refactor: rename CoupledWidth

---

docs/conf.py
docs/index.md
tox.ini

Branch name in `conf.py` is now extracted [from Read the Docs](https://docs.readthedocs.io/en/stable/builds.html) if possible. This way, all Binder/Colab links lead to the corresponding branch or tag of the repo.

docs: link to correct version on Binder/Colab

---

.vscode/settings.json
src/ampform/kinematics.py
src/ampform/sympy/math.py
tests/test_kinematics.py

Classes like `ArrayAxisSum` were specifically using statements like
```python
printer.module_imports["numpy"].add("sum")
```
This is problematic in TensorWaves, which would like to see `"jnp"` and `"tnp"` there (the NumPy interfaces of JAX and TensorFlow). This PR makes this possible.
Another major improvements: `einsum` in `ArrayMultiplication` is used in such a way that `transpose` is not necessary anymore. In addition, an ellipsis return statement is specificied (`"...ij,...j->...i"` instead of `"...ij,...j"`), which [`tf.einsum`](https://www.tensorflow.org/api_docs/python/tf/einsum) requires.

fix: use sympy printer module_imports

---

docs/abbreviate_signature.py
docs/conf.py
src/symplot/__init__.py

`TypeGuard` requires `typing-extensions` v3.10, which is not available to TensorFlow <2.7. With this PR, it is only required when doing style checks.

fix: put TypeGuard under TYPE_CHECKING

---

.cspell.json
docs/usage/amplitude.ipynb
src/ampform/helicity/__init__.py
src/ampform/kinematics.py
tests/helicity/test_helicity.py

feat: implement permutate_registered_topologies

---

codecov.yml
docs/usage/amplitude.ipynb
src/ampform/dynamics/__init__.py
src/ampform/dynamics/builder.py
tox.ini

Closes #205 
This adds a new class, [`RelativisticBreitWignerBuilder`](https://ampform--206.org.readthedocs.build/en/206/api/ampform.dynamics.builder.html#ampform.dynamics.builder.RelativisticBreitWignerBuilder), which makes it possible to insert different kinds of [`PhaseSpaceFactorProtocol`](https://ampform.readthedocs.io/en/0.12.1/api/ampform.dynamics.html#ampform.dynamics.PhaseSpaceFactorProtocol)s into [`set_dynamics()`](https://ampform.readthedocs.io/en/0.12.x/api/ampform.helicity.html#ampform.helicity.HelicityAmplitudeBuilder.set_dynamics). See [here](https://ampform--206.org.readthedocs.build/en/206/usage/amplitude.html#set-dynamics) how to use.
Essentially, this class is an extension of builder functions such as [`create_relativistic_breit_wigner_with_ff()`](https://ampform.readth …

feat: implement RelativisticBreitWignerBuilder

---

docs/_extend_docstrings.py
docs/_relink_references.py
docs/conf.py
docs/usage/formalism.ipynb
src/ampform/helicity/__init__.py
src/ampform/kinematics.py
src/ampform/sympy/__init__.py
src/ampform/sympy/_array_expressions.py
src/ampform/sympy/math.py
tests/sympy/test_array_expressions.py
tests/test_kinematics.py

Preview [here](https://ampform--211.org.readthedocs.build/en/211/api/ampform.kinematics.html). Compare to [v0.12.2](https://ampform.readthedocs.org/en/0.12.2/api/ampform.kinematics.html).
- Definitions in the API are follow the sorting of the source code.
- Hidden the classes for SymPy ArraySymbols by moving them to `ampform.sympy._array_expresssions`.
- Added docstrings to all remaining classes, like `BoostZ`.
- Improved the `docs/_extend_docstrings.py` script.
- Hidden several methods and attributes that come from `sympy.Basic`.
- See [commit history]() for other changes.

docs: clean up API of kinematics module

---

.readthedocs.yml

[`sphinx-apidoc`](https://www.sphinx-doc.org/en/master/man/sphinx-apidoc.html) does not render the docstring for the `FourMomentumSymbol` type alias (#211) when running on Python 3.7. See for instance the [API preview of the latest PR](https://ampform--214.org.readthedocs.build/en/214/api/ampform.kinematics.html#ampform.kinematics.FourMomentumSymbol). The docstring is correctly rendered when building with Python 3.8, see preview [here]().
Note: RTD for QRules also switched to Python 3.8 in https://github.com/ComPWA/qrules/pull/136.

ci: run RTD on Python 3.8

---

docs/_extend_docstrings.py
src/ampform/dynamics/__init__.py
src/ampform/dynamics/builder.py
src/ampform/helicity/naming.py
src/ampform/kinematics.py
src/ampform/sympy/_array_expressions.py
src/symplot/__init__.py
tests/sympy/test_array_expressions.py
tests/test_kinematics.py

`ArrayMultiplication` lambdified to a recursive call to [`einsum()`](https://numpy.org/doc/stable/reference/generated/numpy.einsum.html), which results in larger lambdified code. This PR lambdifies the code to an einsum path, e.g. `...ij,...jk->...i`.

chore: simplify einsum rendering ArrayMultiplication

---

.constraints/py3.10.txt
.constraints/py3.6.txt
.constraints/py3.7.txt
.constraints/py3.8.txt
.constraints/py3.9.txt
tests/test_angular_distributions.py

See release notes [QRules v0.9.6](https://github.com/ComPWA/qrules/releases/tag/0.9.6). Required for a consistent determination of opposite helicity states, see #212.
_Note that this can change helicity angle labels! See a324c9e_

build: upgrade to QRules v0.9.6

---

docs/usage/amplitude.ipynb
docs/usage/interactive.ipynb
src/ampform/kinematics.py
tests/helicity/test_helicity.py
tests/symplot/test_symplot.py
tests/test_angular_distributions.py
tests/test_kinematics.py

Closes #208 
Compare [old notation](https://ampform.readthedocs.io/en/0.12.2/api/ampform.kinematics.html#ampform.kinematics.get_helicity_angle_label) and [new notation](https://ampform--209.org.readthedocs.build/en/209/api/ampform.kinematics.html#ampform.kinematics.get_helicity_angle_label).

refactor: improve helicity angle notation

---

docs/conf.py

Links to NumPy API are now also embedded correctly in the code examples. Follow-up to #217.

docs: show second level in left sidebar

---

.cspell.json
.flake8
docs/_relink_references.py
src/ampform/kinematics.py
src/ampform/sympy/__init__.py

API of the [`ampform.sympy`](https://ampform--213.org.readthedocs.build/en/213/api/ampform.sympy.html) module has become more self-explanatory through the addition of a [`NumPyPrintable`](https://ampform--213.org.readthedocs.build/en/213/api/ampform.sympy.html#ampform.sympy.NumPyPrintable) interface and several explanations and doctests in related classes and decorator functions. Preview [here](https://ampform--213.org.readthedocs.build/en/213/api/ampform.sympy.html).

refactor: extract NumPyPrintable class

---

src/ampform/helicity/__init__.py
src/ampform/helicity/decay.py
src/ampform/helicity/naming.py
src/ampform/kinematics.py
tests/helicity/test_decay.py
tests/test_kinematics.py

Cleaned up the `kinemetics` module by moving `determine_attached_final_state()` to `helicity.decay` and `get_helicity_angle_label()` to `helicity.naming`. Also extracted `get_boost_chain_suffix()` from `get_helicity_angle_label()` in preparation of #212.

refactor: remove decay/naming functions from kinematics

---

docs/_relink_references.py
src/ampform/helicity/__init__.py
src/symplot/__init__.py
tests/helicity/test_helicity.py

#228 has made some parameter names even longer and harder to get with `dict.__getitem__()`. This PR wraps the `parameter_defaults` in a `ParameterValues` class that allows doing stuff like:
```python
>>> import sympy as sp
>>> a, b, c = sp.symbols("a b c")
>>> from ampform.helicity import ParameterValues
>>> parameters = ParameterValues({a: 0.0, b: 1+1j, c: -2})
>>> parameters[a]  # get by sympy.Symbol
0.0
>>> parameters["b"]  # get by str name
(1+1j)
>>> parameters["b"] = 3  # get by position in OrderedDict
>>> parameters[1]
3
>>> parameters[2]
-2
>>> parameters[2] = 3.14  # set by position in OrderedDict
>>> parameters[c]
3.14
```
Note that, as opposed to the previously used `OrderedDict`, this class prevents users from adding more parameters to the `parameter_defaults`.

feat: wrap parameter_defaults in ParameterValues class

---

src/ampform/helicity/__init__.py
src/ampform/helicity/decay.py
tests/helicity/test_decay.py
tox.ini

Removed the check for integral angular momentum. Instead, AmpForm now checks for angular momentum when formulating a form factor. This allows formulating Breit-Wigner dynamics _without_ form factor on an amplitude model formulated with `formalism="helicity"` if it has with half-spin resonances.

fix: check for angular momentum in form factor

---

.cspell.json
docs/_extend_docstrings.py
docs/conf.py
src/ampform/kinematics.py
src/ampform/sympy/__init__.py
src/ampform/sympy/_array_expressions.py
tests/conftest.py
tests/test_kinematics.py

Closes #231 
Extracted [`NumPyPrintable`](https://ampform--232.org.readthedocs.build/en/232/api/ampform.sympy.html#ampform.sympy.NumPyPrintable) implementation classes from [`BoostZMatrix`](https://ampform--232.org.readthedocs.build/en/232/api/ampform.kinematics.html#ampform.kinematics.BoostZMatrix), [`RotationYMatrix`](https://ampform--232.org.readthedocs.build/en/232/api/ampform.kinematics.html#ampform.kinematics.RotationYMatrix) and [`RotationZMatrix`](https://ampform--232.org.readthedocs.build/en/232/api/ampform.kinematics.html#ampform.kinematics.RotationZMatrix), so that the code generated with [`sympy.lambdify()`](https://docs.sympy.org/latest/modules/utilities/lambdify.html#sympy.utilities.lambdify.lambdify) decreases and has a smaller memory footprint (if using `cse=True`). This …

chore: simplify numpy code of matrix expressions

---

docs/usage/amplitude.ipynb
src/ampform/dynamics/builder.py
tests/dynamics/test_builder.py

It's now possible to independently activate energy-dependent width and a form factor in the [`RelativisticBreitWignerBuilder`](https://ampform--236.org.readthedocs.build/en/236/api/ampform.dynamics.builder.html#ampform.dynamics.builder.RelativisticBreitWignerBuilder).
Usage example [here](https://ampform--236.org.readthedocs.build/en/236/usage/amplitude.html#set-dynamics). See also #235.

feat: add switch for energy-dependent width

---

.constraints/py3.10.txt
.constraints/py3.6.txt
.constraints/py3.7.txt
.constraints/py3.8.txt
.constraints/py3.9.txt
.github/workflows/ci-tests.yml
.pre-commit-config.yaml
docs/conf.py
setup.cfg
src/ampform/helicity/__init__.py
src/ampform/helicity/decay.py
src/symplot/__init__.py

`HelicityAmplitudeBuilder.__dynamics_choices` has been extracted to a new `DynamicsSelector` class. This reduces the responsibilities of the `HelicityAmplitudeBuilder` and makes it easier to implement new implementations for selection of dynamics.
Something similar has been done for 'collector' attributes like `HelicityAmplitudeBuilder.__parameter_defaults` and `__components`. This will be useful when implementing [TR-014](https://compwa-org.readthedocs.io/report/014.html), which will require keeping track of amplitude definitions.
Note: once QRules v0.10 is out, https://github.com/ComPWA/qrules/pull/156 and https://github.com/ComPWA/qrules/pull/157 make it possible to define the dynamics choices as a mapping over topologies and visualize them as graphviz.

feat: extract DynamicsSelector class

---

src/ampform/helicity/__init__.py
src/ampform/kinematics.py

Implementation of the [`HelicityAdapter`](https://ampform.readthedocs.io/en/0.12.3/api/ampform.kinematics.html#ampform.kinematics.HelicityAdapter) class was a bit too complicated. This PR makes the class into a simple manager of Topology instances that can create expressions from these topologies. Interface hasn't changed though.

refactor: simplify HelicityAdapter class

---

docs/_relink_references.py
src/ampform/helicity/__init__.py
tox.ini

Note: it's not yet possible to abbreviate type aliases in nested type hints. Sphinx will fix this (https://github.com/sphinx-doc/sphinx/pull/10183) in [v4.5.0](https://www.sphinx-doc.org/en/master/changes.html#release-4-5-0-in-development). This will also make it possible to improve the order of definitions in the `helicity` module (makes more sense to define `HelicityModel` first). See also https://github.com/ComPWA/compwa-org/issues/116.

fix: improve signatures in helicity module

---

docs/usage/modify.ipynb
src/ampform/helicity/__init__.py
src/ampform/sympy/__init__.py
src/symplot/__init__.py
tests/helicity/test_helicity.py

See use case example [here]() (couple parameters). The method is makes it easier to address [this error](https://github.com/ComPWA/ampform/runs/5320069236?check_suite_focus=true) in #243.

feat: implement HelicityModel.rename_symbols()

---

docs/_extend_docstrings.py
docs/usage/dynamics/k-matrix.ipynb
pytest.ini
src/ampform/dynamics/__init__.py
src/ampform/dynamics/builder.py
src/ampform/dynamics/kmatrix.py
tests/dynamics/test_builder.py

Extracted the formulation of the production form factor in [PDG2021 Equation (50.26)](https://pdg.lbl.gov/2021/reviews/rpp2021-rev-resonances.pdf#page=9) as a separate function. See [this preview]() for the formula.
It formulates a special version of (the square root of) `BlattWeisskopfSquared`, with break-up momentum and a meson radius (impact parameter) and is used in `relativistic_breit_wigner_with_ff()`, `RelativisticPVector`, `create_non_dynamic_with_ff()`, etc.
This PR might solve #261: if something needs to be changed there, one simply needs to modify this new `formulate_form_factor()` function.
--- 
Also updated all PDG references to PDG2021.

refactor: extract formulate_form_factor()

---

docs/_extend_docstrings.py
docs/usage/dynamics.ipynb
docs/usage/dynamics/analytic-continuation.ipynb
src/ampform/dynamics/__init__.py
src/ampform/dynamics/builder.py
tests/dynamics/test_sympy.py
tests/test_dynamics.py
tox.ini

[`PhaseSpaceFactorAnalytic`](https://ampform.readthedocs.io/en/0.13.3/api/ampform.dynamics.html#ampform.dynamics.PhaseSpaceFactorAnalytic) has been renamed to [`EqualMassPhaseSpaceFactor`](https://ampform--264.org.readthedocs.build/en/264/api/ampform.dynamics.html#ampform.dynamics.EqualMassPhaseSpaceFactor).
`PhaseSpaceFactorAnalytic` was a bit of a misleading name: it only works if the masses of the decay products are _equal_. This should instead be addressed by implementing [[TR-003]](https://compwa-org.rtfd.io/report/003.html), which will result in (yet) another phase space factor expression class.

refactor: rename PhaseSpaceFactorAnalytic

---

.cspell.json
docs/_extend_docstrings.py
docs/usage/dynamics.ipynb
docs/usage/dynamics/analytic-continuation.ipynb
src/ampform/dynamics/__init__.py
src/ampform/dynamics/phasespace.py
tests/sympy/test_math.py

This PR moves all functions and classes related to phase space factors to a new module, [`ampform.dymamics.phasespace`](), so that the [`ampform.dymamics`]() becomes easier to understand. This has become even more important since the addition of yet another phase space factor in #265 and potentially even more when implementing the [dispersion integral](https://compwa-org.readthedocs.io/report/003.html#general-dispersion-integral) from [TR-003](https://compwa-org.readthedocs.io/report/003.html).

refactor: move phsp factors to separate module

---

docs/usage/amplitude.ipynb
src/ampform/helicity/__init__.py
src/ampform/helicity/decay.py
src/ampform/helicity/naming.py
src/ampform/kinematics.py
tests/test_kinematics.py

Some renames:
- [`get_helicity_angle_label()`](https://ampform.readthedocs.io/en/0.13.3/api/ampform.helicity.naming.html#ampform.helicity.naming.get_helicity_angle_label) → [`get_helicity_angle_symbols()` ](https://ampform--269.org.readthedocs.build/en/269/api/ampform.helicity.naming.html#ampform.helicity.naming.get_helicity_angle_symbols)
- [`get_invariant_mass_label()`](https://ampform.readthedocs.io/en/0.13.3/api/ampform.kinematics.html#ampform.kinematics.get_invariant_mass_label) → [`get_invariant_mass_symbol()`](https://ampform--269.org.readthedocs.build/en/269/api/ampform.kinematics.html#ampform.kinematics.get_invariant_mass_symbol)
They now return [`sympy.Symbol`](https://docs.sympy.org/latest/modules/core.html#sympy.core.symbol.Symbol)s instead of strings, so that assumptions can …

refactor: return sympy.Symbol instead of str

---

docs/_extend_docstrings.py
src/ampform/sympy/math.py
tests/sympy/test_math.py

This prevents [ComplexSqrt](https://ampform.readthedocs.io/en/0.13.3/api/ampform.sympy.math.html#ampform.sympy.math.ComplexSqrt) from evaluating on `sympy.Expr` input, which is important when `Symbol` assumptions are changed (#268).

refactor: block ComplexSqrt from evaluating

---

docs/usage/dynamics/analytic-continuation.ipynb
src/ampform/dynamics/phasespace.py

BEHAVIOR: remove factor 16 pi from phsp factor

---

src/ampform/io/__init__.py

Follow-up to #413 that allows passing keyword arguments to the [`Iterable`](https://docs.python.org/3/library/typing.html#typing.Iterable) implementation of [`aslatex()`](https://ampform.readthedocs.io/0.15.x/api/ampform.io/#ampform.io.aslatex).

FIX: pass `kwargs` in `aslatex` iterable implementation

---

docs/_extend_docstrings.py
docs/conf.py
src/ampform/sympy/_decorator.py

Arguments that are sympified were previously rendered as class attributes. This PR hides them from API of the expression classes (if they do not have a `__doc__` docstring), because they are already visible in the signature of the class.

DOC: hide sympified attributes from expression classes

---

docs/_extend_docstrings.py
src/ampform/dynamics/__init__.py

Fix-up to #422, which redefined `EnergyDependentWidth` as (see [v0.15.2](https://ampform.readthedocs.io/0.15.2/api/ampform.dynamics/#ampform.dynamics.EnergyDependentWidth))
```math
\Gamma_{0}\left(s\right) = \frac{\Gamma_{0} \mathcal{F}_{L}\left(s, m_{a}, m_{b}\right) \rho\left(s\right)}{\mathcal{F}_{L}\left(m_{0}^{2}, m_{a}, m_{b}\right) \rho_{0}\left(m_{0}^{2}\right)}
```
instead of  (see [v0.15.1](https://ampform.readthedocs.io/0.15.1/api/ampform.dynamics/#ampform.dynamics.EnergyDependentWidth))
```math
\Gamma_{0}\left(s\right) = \frac{\Gamma_{0} B_{L}^2\left(q^2\left(s\right)\right) \rho\left(s\right)}{B_{L}^2\left(q^2_{0}\left(m_{0}^{2}\right)\right) \rho_{0}\left(m_{0}^{2}\right)}\,.
```
This is not equivalent, because [`FormFactor`](https://ampform.readthedocs.io/0.15.2/api/ampform. …

FIX: use squared `FormFactor` in `EnergyDependentWidth`

---

src/ampform/dynamics/form_factor.py
tests/dynamics/test_dynamics.py
tests/dynamics/test_form_factor.py

Closes #426 
Improves the benchmark implemented in #427 by **3x** 🎉 
- This PR: [**6.78s**](https://github.com/ComPWA/ampform/actions/runs/9191700337/job/25278673860?pr=428#step:4:47)
- Main branch (effb0de): [**20.93s**](https://github.com/ComPWA/ampform/actions/runs/9191526669/job/25278371300#step:4:47)

ENH: cache Blatt–Weisskopf polynomials

---

.constraints/py3.10.txt
.constraints/py3.11.txt
.constraints/py3.12.txt
.constraints/py3.8.txt
.constraints/py3.9.txt
docs/usage/dynamics/k-matrix.ipynb
pyproject.toml
src/ampform/dynamics/__init__.py
src/ampform/dynamics/builder.py
src/ampform/dynamics/kmatrix.py
src/ampform/kinematics/lorentz.py
src/ampform/sympy/__init__.py
src/ampform/sympy/_decorator.py
src/ampform/sympy/deprecated.py
src/ampform/sympy/math.py
tests/dynamics/test_deprecated.py
tests/dynamics/test_dynamics.py
tests/dynamics/test_kmatrix.py

See SymPy release notes for [v1.13.0](https://github.com/sympy/sympy/wiki/release-notes-for-1.13.0) and  [v1.13.1](https://github.com/sympy/sympy/wiki/release-notes-for-1.13.1).

MAINT: upgrade to SymPy v1.13

---

.cspell.json
.github/workflows/benchmark.yml
.github/workflows/ci-qrules-v0.9.yml
.github/workflows/ci.yml
.pre-commit-config.yaml
.vscode/extensions.json
.vscode/settings.json
pyproject.toml
src/ampform/helicity/__init__.py
src/ampform/helicity/decay.py
src/ampform/helicity/naming.py
src/ampform/kinematics/lorentz.py
src/ampform/sympy/__init__.py
src/ampform/sympy/_array_expressions.py
src/ampform/sympy/_decorator.py
src/ampform/sympy/deprecated.py
src/ampform/sympy/math.py
uv.lock

- Closes https://github.com/ComPWA/policy/issues/465

MAINT: update lock files

---

.vscode/settings.json
docs/usage/sympy.ipynb
src/ampform/helicity/__init__.py
src/ampform/sympy/__init__.py
src/symplot/__init__.py
tests/external/test_sympy.py

- Imported `partial_doit()` from `symplot` into `ampform.sympy`
- Also gave it the option to unfold recursively and added tests and documentation
- Related to https://github.com/ComPWA/ampform/issues/279

FEAT: implement `partial_doit()` function

---

docs/usage/amplitude.ipynb
src/ampform/sympy/cached.py
tests/sympy/test_cached.py

Implemented a convenience function, `cached.unfold()`, which does two things:
1. It combines and 'unfolds' (evaluates) the `model.intensity` and its `model.amplitudes` in one go.
1. It unfolds and combines a top expression (like `model.intensity`) and its definitions (like `model.amplitudes`) efficiently by first calling `doit` on the top expression, then calling `doit` on all the expressions in the definitions, and finally combining them with `xreplace`. This is more efficient than using `xreplace` and then `doit` on the whole result. The function also uses caching internally.
Note that `cached.unfold` takes either a single amplitude model or a top expression and a list of definitions. This is motivated by [ComPWA/polarimetry](https://github.com/ComPWA/polarimetry), where instead of …

FEAT: implement `cached.unfold` for amplitude models

---

src/ampform/sympy/_cache.py
src/ampform/sympy/cached.py

The `@cache_to_disk` decorator got some major improvements:
- It embeds the model name and its own name into the hash.
- It got a `dependencies` keyword that allows specifying which dependencies the function has. The distribution names plus their version (minus any `dev` identifiers) are then included into the hash as well to improve cache invalidation.
- Hash files are now organised like objects in a `.git` folder (e.g. `83/c88eef607e4ff33e11bf626c784d73`).
- The `dump` and `load` methods can be overwritten. This is useful for `perform_cache_lambdify()` in AmpForm-DPD.
- Hashes should be more stable now: any `dict`s in function arguments are sorted now.
- Warning messages for missing caches or `NO_CACHE` are improved.

ENH: improve cache invalidation of `@cache_to_disk`

---

.github/workflows/benchmark.yml
docs/index.md

See https://github.com/ComPWA/policy/issues/514
> [!WARNING]
> This changes the URL for the benchmark results from compwa.github.io/ampform to **[compwa.github.io/ampform-benchmark-results](https://compwa.github.io/ampform-benchmark-results)**.

DX: host benchmark results on separate repository

---

.github/workflows/redirect-gh-pages.yml

Follow-up to #460: [compwa.github.io/ampform](https://compwa.github.io/ampform) is now redirected to **[compwa.github.io/ampform-benchmark-results](https://compwa.github.io/ampform-benchmark-results)**.

DOC: redirect compwa.github.io/ampform to benchmark page

---

.github/workflows/ci.yml
.pre-commit-config.yaml
src/ampform/sympy/cached.py
tests/sympy/test_cache_helpers.py

This stabilizes the hash of amplitude models that contain `sympy.Indexed` symbols.
> [!WARNING]
> The hashes are still not fully stable!

ENH: convert to `sp.Symbol` before computing `unfold` hash

---

docs/_extend_docstrings.py
src/ampform/sympy/_cache.py
tests/sympy/test_cache_helpers.py

This speeds up `get_readable_hash()` by enforcing objects to be hashable.

ENH: memoize `get_readable_hash()`

---

src/ampform/sympy/cached.py
tests/sympy/test_cache_helpers.py

This reverts the implementation of #465 (but not the tests). See https://github.com/ComPWA/ampform-dpd/discussions/163.

BEHAVIOR: keep `sp.Indexed` in `unfold()` hash

---

src/ampform/sympy/_cache.py

This is a fix-up to #459. The values of mappings were not made hashable. Some other improvements can be found in the [commits](https://github.com/ComPWA/ampform/commits).

FIX: make values in mapping hashable
