ComPWA/ampform

- docs/usage/amplitude.ipynb
- tests/conftest.py
- tests/test_dynamics.py
- tests/test_helicity.py
Import tests introduced by #20
> ci: merge master into epic branch

- reqs/3.6/requirements-dev.txt
- reqs/3.6/requirements-doc.txt
- reqs/3.7/requirements-dev.txt
- reqs/3.7/requirements-doc.txt
- reqs/3.8/requirements-dev.txt
- reqs/3.8/requirements-doc.txt
- reqs/3.9/requirements-dev.txt
- reqs/3.9/requirements-doc.txt
- reqs/requirements-dev.in
- reqs/requirements-doc.in
- tox.ini
In particular `ipywidgets` (which may be added later on again in the dynamics epic branch).
> ci: remove redundant dev dependencies

- .pylintrc
- setup.cfg
- src/ampform/data.py
- src/ampform/dynamics/lineshape.py
- tests/external/test_sympy.py
- tests/test_dynamics.py
* Remove built-ins check (flake8-builtins handles this)
* Sort pylintrc sections
* Use `good-names-rgxs`
* Use error names instead of error codes
* Move some of the ignores inline
> ci: clean up pylint configuration

- .constraints/py3.6.txt
- .constraints/py3.7.txt
- .constraints/py3.8.txt
- .constraints/py3.9.txt
- .flake8
- docs/usage/amplitude.ipynb
- setup.cfg
- src/ampform/_graph_info.py
- src/ampform/helicity.py
- src/ampform/kinematics.py
- tests/test_angular_distributions.py
- tests/test_angular_momentum.py
- tests/test_data.py
- tests/test_dynamics.py
- tests/test_helicity.py
- tests/test_parity_prefactor.py
- [`flake8-comprehensions`](https://pypi.org/project/flake8-comprehensions)
- [`flake8-pytest-style`](https://pypi.org/project/flake8-pytest-style)
- [`flake8-use-fstring`](https://github.com/MichaelKim0407/flake8-use-fstring/blob/develop/README.md)
> ci: add more flake8 plugins and fix issues

- docs/extend_docstrings.py
- docs/usage/dynamics/k-matrix.ipynb
- docs/usage/dynamics/lineshapes.ipynb
- src/ampform/dynamics/__init__.py
- src/ampform/dynamics/builder.py
- tests/test_dynamics.py
Comparable to #48, this allows handling negative values of 𝑠 or 𝑚².
> refactor!: use Mandelstam s instead of m²

- docs/extend_docstrings.py
- docs/usage/dynamics/lineshapes.ipynb
> docs: add interactive dynamics lineshape widgets

- tests/conftest.py
- tests/test_angular_distributions.py
- tests/test_dynamics.py
- tests/test_helicity.py
- tests/test_parity_prefactor.py
Some improvements to the test set-up.
> test: parametrize fixtures

- docs/usage.md
- docs/usage/modify.ipynb
First step towards #5. Adds a new page that shows some SymPy tricks to modify the `HelicityModel`.
> docs: explain how to substitute parameters

- docs/usage/modify.ipynb
> docs: illustrate how to couple parameters

- docs/usage/amplitude.ipynb
- src/ampform/helicity/__init__.py
- tests/helicity/test_helicity.py
Import [`tensorwaves.physics.add_components`](https://tensorwaves.readthedocs.io/en/0.2.8/api/tensorwaves.physics.html#tensorwaves.physics.add_components).
> feat: implement HelicityModel.sum_components

- .github/workflows/ci-style.yml
- .pre-commit-config.yaml
- README.md
- tox.ini
See ComPWA/qrules#87
Should fix CI for d5cb237
> ci!: switch to pre-commit.ci where possible

- src/symplot/__init__.py
Implementation of [[TR-008] `Indexed` free symbols](https://compwa-org.readthedocs.io/en/stable/report/008.html)
> feat: implement indexed_to_symbol from TR-008

- .cspell.json
- src/symplot/__init__.py
Helper function for https://github.com/ComPWA/compwa-org/pull/37
> feat: implement symplot.partial_doit

- src/ampform/helicity/__init__.py
- src/ampform/helicity/decay.py
- src/ampform/helicity/naming.py
See https://github.com/ComPWA/ampform/pull/100#issuecomment-886250406
> refactor: remove angular momentum projection

- docs/usage/dynamics/k-matrix.ipynb
- src/ampform/dynamics/kmatrix.py
> feat!: implement relativistic P-vector

- src/symplot/__init__.py
Sometimes, you want to plot an expression with respect to several variables (like an _XY_-plot). This commit facilitates that.
> feat: use more plot symbols in prepare_sliders

- README.md
- setup.cfg
Also removed the tickboxes there, as they do not render correctly on PyPI
> docs: extend package description in README

- .constraints/py3.10.txt
- .constraints/py3.6.txt
- .constraints/py3.7.txt
- .constraints/py3.8.txt
- .constraints/py3.9.txt
- .github/workflows/cd.yml
- .pre-commit-config.yaml
623f6a1 should fix https://github.com/ComPWA/ampform/actions/runs/1541335126
> ci: update pip constraints and pre-commit config

- .constraints/py3.10.txt
- .constraints/py3.6.txt
- .constraints/py3.7.txt
- .constraints/py3.8.txt
- .constraints/py3.9.txt
- .pre-commit-config.yaml
- src/ampform/helicity/__init__.py
* With https://github.com/ComPWA/qrules/pull/130 and f08f1f0, `import ampform` is about 2x as fast
* Updated `pip` constraint files
* Updated `.pre-commit-config.yaml` file
> feat: speed up imports

- docs/usage/amplitude.ipynb
- src/ampform/helicity/__init__.py
- tests/helicity/test_helicity.py
> feat: implement stable final state switch

- .constraints/py3.10.txt
- .constraints/py3.6.txt
- .constraints/py3.7.txt
- .constraints/py3.8.txt
- .constraints/py3.9.txt
- .github/workflows/ci-docs.yml
- .pre-commit-config.yaml
- docs/usage/amplitude.ipynb
- docs/usage/dynamics.ipynb
- docs/usage/dynamics/analytic-continuation.ipynb
- docs/usage/dynamics/custom.ipynb
- docs/usage/dynamics/k-matrix.ipynb
- docs/usage/formalism.ipynb
- docs/usage/interactive.ipynb
- docs/usage/modify.ipynb
- docs/usage/symplot.ipynb
- setup.cfg
Closes https://github.com/ComPWA/repo-maintenance/issues/43
[![image](https://user-images.githubusercontent.com/29308176/149676020-8281cbb4-8cae-4e1a-a171-b451809ea993.png)](https://ampform--204.org.readthedocs.build/en/204/usage/amplitude.html)
> docs: add notebook button for Deepnote

- docs/usage/amplitude.ipynb
- src/ampform/helicity/__init__.py
- tests/helicity/test_helicity.py
Follow-up to #197. See usage [here]().
> feat: implement scalar initial state mass switch

- docs/conf.py
- docs/usage/amplitude.ipynb
- docs/usage/modify.ipynb
Compare [old](https://ampform--219.org.readthedocs.build/en/219/usage/amplitude.html#extend-kinematic-variables) with [new](https://ampform--220.org.readthedocs.build/en/220/usage/amplitude.html#extend-kinematic-variables).
> fix: render graphviz.Source as link

- .github/workflows/ci-tests.yml
> ci: include doctests in test coverage

- .constraints/py3.10.txt
- .constraints/py3.6.txt
- .constraints/py3.7.txt
- .constraints/py3.8.txt
- .constraints/py3.9.txt
- .pre-commit-config.yaml
- docs/conf.py
- docs/usage/amplitude.ipynb
- docs/usage/dynamics.ipynb
- docs/usage/dynamics/analytic-continuation.ipynb
- docs/usage/dynamics/custom.ipynb
- docs/usage/dynamics/k-matrix.ipynb
- docs/usage/formalism.ipynb
- docs/usage/interactive.ipynb
- docs/usage/modify.ipynb
- docs/usage/symplot.ipynb
See "New features" under https://github.com/ComPWA/repo-maintenance/pull/49
> docs: add IPython.display import to notebooks

- docs/install.md
Preview [here](https://ampform--233.org.readthedocs.build/en/233/install.html). See also https://github.com/ComPWA/tensorwaves/pull/411.
> docs: clarify pinned dependencies with Conda

- .github/workflows/requirements-cron.yml
- .pre-commit-config.yaml
- .pylintrc
- docs/_extend_docstrings.py
- docs/_relink_references.py
- src/ampform/dynamics/builder.py
- src/ampform/helicity/__init__.py
- src/ampform/helicity/decay.py
- src/ampform/kinematics.py
See [`import attrs`](https://hynek.me/articles/import-attrs/#the-last-step-import-attrs) and [`attrs` TNG](https://www.attrs.org/en/21.4.0/names.html#attrs-tng).
> chore: switch to new import attrs API

- .github/workflows/ci-docs.yml
- .github/workflows/ci-style.yml
- .github/workflows/ci-tests.yml
- .github/workflows/linkcheck.yml
- .gitpod.yml
- .pre-commit-config.yaml
- .vscode/extensions.json
- .vscode/settings.json
This makes it safer to commit or PR patches to older versions.
> ci: run GitHub Actions on version branches

- .constraints/py3.10.txt
- .constraints/py3.7.txt
- .constraints/py3.8.txt
- .constraints/py3.9.txt
- docs/_relink_references.py
- docs/conf.py
- setup.cfg
- src/ampform/dynamics/__init__.py
- src/ampform/dynamics/builder.py
- src/ampform/dynamics/kmatrix.py
- src/ampform/helicity/__init__.py
- src/ampform/helicity/decay.py
- src/ampform/helicity/naming.py
- src/ampform/kinematics.py
- src/ampform/sympy/__init__.py
- src/ampform/sympy/_array_expressions.py
- src/ampform/sympy/math.py
- src/symplot/__init__.py
- tests/conftest.py
- tests/dynamics/test_kmatrix.py
- tests/helicity/test_decay.py
- tests/helicity/test_helicity.py
- tests/symplot/test_symplot.py
- tests/test_angular_distributions.py
- tests/test_dynamics.py
- tests/test_kinematics.py
See [PEP 563](https://www.python.org/dev/peps/pep-0563) and https://github.com/ComPWA/compwa-org/issues/116.
> chore: simplify type hints with PEP 563

- docs/usage/amplitude.ipynb
- src/ampform/helicity/__init__.py
- src/ampform/helicity/naming.py
- tests/helicity/test_helicity.py
Closes #254. See documentation preview [here](https://ampform--256.org.readthedocs.build/en/256/usage/amplitude.html#helicity-couplings).
> feat: implement switch for helicity couplings

- docs/usage/dynamics/k-matrix.ipynb
2D part of [the _K_-matrix](https://ampform.readthedocs.io/en/0.13.x/usage/dynamics/k-matrix.html) notebook previously raised an exception and froze upon updates to the widgets. This PR fixes that.
> fix: remove selection on mesh grid

- .github/release-drafter.yml
- .readthedocs.yml
- Implemented https://github.com/ComPWA/tensorwaves/pull/429
- Implemented https://github.com/ComPWA/repo-maintenance/issues/55
> ci: pin all dependencies on Read the Docs

- .github/workflows/benchmark.yml
- .pre-commit-config.yaml
- .vscode/settings.json
- benchmarks/conftest.py
- benchmarks/doit_speed.py
- docs/index.md
- pyproject.toml
- tox.ini
- Implements a benchmark test for https://github.com/ComPWA/ampform/issues/426
- See https://github.com/ComPWA/policy/issues/63
> DX: implement benchmark monitoring
